ln -sf whatis.exe /bin/apropos
ln -sf gawk.exe /bin/awk
ln -sf bzdiff /bin/bzcmp
ln -sf bzgrep /bin/bzegrep
ln -sf bzgrep /bin/bzfgrep
ln -sf bzmore /bin/bzless
ln -sf cygicudata48.dll /bin/cygicudata.dll
ln -sf cygicui18n48.dll /bin/cygicui18n.dll
ln -sf cygicuio48.dll /bin/cygicuio.dll
ln -sf cygicule48.dll /bin/cygicule.dll
ln -sf cygiculx48.dll /bin/cygiculx.dll
ln -sf cygicutest48.dll /bin/cygicutest.dll
ln -sf cygicuuc48.dll /bin/cygicuuc.dll
ln -sf hostname.exe /bin/dnsdomainname
ln -sf hostname.exe /bin/domainname
ln -sf vi.exe /bin/ex
ln -sf xz.exe /bin/lzcat
ln -sf xzdiff /bin/lzcmp
ln -sf xzdiff /bin/lzdiff
ln -sf xzgrep /bin/lzegrep
ln -sf xzgrep /bin/lzfgrep
ln -sf xzgrep /bin/lzgrep
ln -sf xzless /bin/lzless
ln -sf xz.exe /bin/lzma
ln -sf xzmore /bin/lzmore
ln -sf python2.7.exe /bin/python
ln -sf python2.7-config /bin/python-config
ln -sf python2.7.exe /bin/python2
ln -sf python2.7-config /bin/python2-config
ln -sf nano /bin/rnano
ln -sf vi.exe /bin/rvi
ln -sf ./ssh.exe /bin/slogin
ln -sf xz.exe /bin/unlzma
ln -sf xz.exe /bin/unxz
ln -sf xz.exe /bin/xzcat
ln -sf xzdiff /bin/xzcmp
ln -sf xzgrep /bin/xzegrep
ln -sf xzgrep /bin/xzfgrep
ln -sf /proc/self/fd /dev/fd 2>/dev/null
ln -sf /proc/self/fd/2 /dev/stderr
ln -sf /proc/self/fd/0 /dev/stdin
ln -sf /proc/self/fd/1 /dev/stdout
ln -sf /usr/share/fontconfig/conf.avail/10-scale-bitmap-fonts.conf /etc/fonts/conf.d/10-scale-bitmap-fonts.conf
ln -sf /usr/share/fontconfig/conf.avail/20-unhint-small-vera.conf /etc/fonts/conf.d/20-unhint-small-vera.conf
ln -sf /usr/share/fontconfig/conf.avail/30-metric-aliases.conf /etc/fonts/conf.d/30-metric-aliases.conf
ln -sf /usr/share/fontconfig/conf.avail/30-urw-aliases.conf /etc/fonts/conf.d/30-urw-aliases.conf
ln -sf /usr/share/fontconfig/conf.avail/40-nonlatin.conf /etc/fonts/conf.d/40-nonlatin.conf
ln -sf /usr/share/fontconfig/conf.avail/45-latin.conf /etc/fonts/conf.d/45-latin.conf
ln -sf /usr/share/fontconfig/conf.avail/49-sansserif.conf /etc/fonts/conf.d/49-sansserif.conf
ln -sf /usr/share/fontconfig/conf.avail/50-user.conf /etc/fonts/conf.d/50-user.conf
ln -sf /usr/share/fontconfig/conf.avail/51-local.conf /etc/fonts/conf.d/51-local.conf
ln -sf /usr/share/fontconfig/conf.avail/60-latin.conf /etc/fonts/conf.d/60-latin.conf
ln -sf /usr/share/fontconfig/conf.avail/65-fonts-persian.conf /etc/fonts/conf.d/65-fonts-persian.conf
ln -sf /usr/share/fontconfig/conf.avail/65-nonlatin.conf /etc/fonts/conf.d/65-nonlatin.conf
ln -sf /usr/share/fontconfig/conf.avail/69-unifont.conf /etc/fonts/conf.d/69-unifont.conf
ln -sf /usr/share/fontconfig/conf.avail/80-delicious.conf /etc/fonts/conf.d/80-delicious.conf
ln -sf /usr/share/fontconfig/conf.avail/90-synthetic.conf /etc/fonts/conf.d/90-synthetic.conf
ln -sf /proc/mounts /etc/mtab
ln -sf /usr/ssl/certs /etc/pki/tls/certs
ln -sf /usr/ssl/certs /etc/ssl/certs
ln -sf python2.7/config/libpython2.7.dll.a /lib/libpython2.7.dll.a
ln -sf ../../bin/update-ca-trust /lib/p11-kit/trust-extract-compat
ln -sf /usr/bin/cygperl5_14.dll /lib/perl5/5.14/i686-cygwin-threads-64int/CORE/cygperl5_14.dll
ln -sf /usr/bin/cygperl5_14_2.dll /lib/perl5/5.14/i686-cygwin-threads-64int/CORE/cygperl5_14_2.dll
ln -sf /etc/pki/ca-trust/extracted/java/cacerts /lib/security/cacerts
ln -sf ../share/terminfo /lib/terminfo
ln -sf alternatives.exe /usr/sbin/update-alternatives
ln -sf ../magic /usr/share/file/magic
ln -sf ../LC_MESSAGES/coreutils.mo /usr/share/locale/fi/LC_TIME/coreutils.mo
ln -sf misc/magic /usr/share/magic
ln -sf ../45/Eterm /usr/share/terminfo/45/Eterm-color
ln -sf ../6b/kon /usr/share/terminfo/6a/jfbterm
ln -sf ../73/screen.xterm-xfree86 /usr/share/terminfo/73/screen.xterm-new
ln -sf zoneinfo /usr/share/zoneinfo-posix
ln -sf /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem /usr/ssl/cert.pem
ln -sf /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem /usr/ssl/certs/ca-bundle.crt
ln -sf /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt /usr/ssl/certs/ca-bundle.trust.crt
ln -sf python2.7/config/libpython2.7.dll.a /usr/lib/libpython2.7.dll.a
ln -sf ../../bin/update-ca-trust /usr/lib/p11-kit/trust-extract-compat
ln -sf /usr/bin/cygperl5_14.dll /usr/lib/perl5/5.14/i686-cygwin-threads-64int/CORE/cygperl5_14.dll
ln -sf /usr/bin/cygperl5_14_2.dll /usr/lib/perl5/5.14/i686-cygwin-threads-64int/CORE/cygperl5_14_2.dll
ln -sf /etc/pki/ca-trust/extracted/java/cacerts /usr/lib/security/cacerts
ln -sf ../share/terminfo /usr/lib/terminfo

WINPATH="$( cygpath "$WINDIR" )"
ln -sf "$WINPATH"/System32/drivers/etc/hosts /etc/hosts
ln -sf "$WINPATH"/System32/drivers/etc/networks /etc/networks
ln -sf "$WINPATH"/System32/drivers/etc/protocols /etc/protocols
ln -sf "$WINPATH"/System32/drivers/etc/services /etc/services
